name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"   # update tiap hari jam 00:00 UTC
  workflow_dispatch:      # bisa dijalankan manual
  push:                   # juga jalan kalau ada push ke repo

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 🔥 WAJIB biar bisa push ke repo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: zidanearyasyifakurniawan   # ganti dengan username GitHub kamu
          outputs: dist/snake.svg

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output   # hasil animasi masuk ke branch "output"
